"""Creative Canvas v2 routes — `/creative/canvas/session/*`.

This module extends the existing v1.x divergence API without breaking
changes. All v1.x endpoints in `creative_diverge.py` remain functional.

Endpoint naming: v2.0 uses `/creative/canvas/session/*` to:
  1. Differentiate from v1.x `/creative/diverge/*` (gradual rollout)
  2. Avoid conflict with wizard step 1's divergence sub-path
  3. Reserve `/creative/canvas/regenerate`, `/finalize`, `/backtrack`
     for v2.1+ deferred features
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException

router = APIRouter(prefix="/creative/canvas", tags=["canvas-v2"])


def _validate_for_commit(canvas: dict) -> None:
    """Validate canvas is ready to commit.

    Checks (spec §4.4):
      1. ≥ 2 steps COMPLETED
      2. No STALE steps
      3. Step 5 specifically COMPLETED (v2.0 MVP — no early-finalize)

    Note: this function does NOT check `final_concept` — final_concept is
    generated by step 2 of the commit handler AFTER step 1 invokes this
    function. Validation of the generated final_concept happens in step 3
    of the commit handler.
    """
    path = canvas.get("creative_path", [])
    completed = [p for p in path if p.get("state") == "completed"]
    if len(completed) < 2:
        raise HTTPException(
            status_code=422,
            detail={
                "error": True,
                "code": "INVALID_PATH",
                "message": "至少需要 2 步 COMPLETED",
                "detail": {},
            },
        )
    stale = [p for p in path if p.get("state") == "stale"]
    if stale:
        raise HTTPException(
            status_code=422,
            detail={
                "error": True,
                "code": "INVALID_PATH",
                "message": f"{len(stale)} 个 STALE 步骤需要处理",
                "detail": {},
            },
        )
    step5 = next((p for p in path if p.get("step") == 5), None)
    if not step5 or step5.get("state") != "completed":
        raise HTTPException(
            status_code=422,
            detail={
                "error": True,
                "code": "INVALID_PATH",
                "message": "Step 5 必须走完(v2.0 MVP 不支持早收束)",
                "detail": {},
            },
        )
