"""Creative Canvas v2 routes — `/creative/canvas/{project_id}/session/*`.

This module extends the existing v1.x divergence API without breaking
changes. All v1.x endpoints in `creative_diverge.py` remain functional.

Endpoint naming: v2.0 uses `/creative/canvas/{project_id}/session/*` to:
  1. Differentiate from v1.x `/creative/diverge/*` (gradual rollout)
  2. Avoid conflict with wizard step 1's divergence sub-path
  3. Reserve `/creative/canvas/regenerate`, `/finalize`, `/backtrack`
     for v2.1+ deferred features
"""
from __future__ import annotations

import asyncio
import json
import logging
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

import yaml
from fastapi import APIRouter, HTTPException, Response
from pydantic import BaseModel, Field

from backend.api.creative_diverge import (
    _ensure_project,
    _read_canvas,
    _write_canvas,
    _compute_etag,
)
from backend.config import settings
from backend.creative_os.state_machine import (
    transition_step_state,
)
from backend.creative_os.op_hint import compute_op_hint
from backend.creative_os.option_generator import format_axis_hint_block

router = APIRouter(prefix="/creative/canvas/{project_id}", tags=["canvas-v2"])

# Must match v1.x InitRequest in backend/api/creative_diverge.py.
_MAX_PROMPT_LEN = 1700

_PROMPTS_DIR = Path(__file__).parent.parent / "prompts"
_NEXT_STEP_PROMPT_PATH = _PROMPTS_DIR / "canvas_v2_next_step.yaml"
_logger = logging.getLogger(__name__)


def _load_next_step_prompt() -> dict:
    """Load next-step prompt template from YAML. Cached after first call."""
    if not hasattr(_load_next_step_prompt, "_cache"):
        with open(_NEXT_STEP_PROMPT_PATH, encoding="utf-8") as f:
            _load_next_step_prompt._cache = yaml.safe_load(f)
    return _load_next_step_prompt._cache


async def _call_llm_with_retry(llm_call, context, max_attempts=2):
    """Call LLM with JSON retry (spec §6.5).

    Retries ONCE on JSON parse failure. The retry sets
    ``context["retry_hint"]`` to "Please return valid JSON only"; the
    caller is responsible for reading this key and prepending it to the
    prompt sent to the LLM on the second attempt. Without that step,
    retries will fail the same way and the helper will raise after
    exhaustion.

    Retry interval is 0 (immediate). Raises RuntimeError after exhaustion.
    """
    last_error = None
    for attempt in range(max_attempts):
        try:
            raw = await llm_call(context)
            return json.loads(raw)
        except (json.JSONDecodeError, ValueError) as exc:
            last_error = exc
            _logger.warning("LLM JSON parse failed on attempt %d: %s", attempt + 1, exc)
            if attempt + 1 < max_attempts:
                context = {**context, "retry_hint": "Please return valid JSON only"}
    raise RuntimeError(
        f"LLM 返回了无效 JSON ({max_attempts} 次): {last_error or 'no attempts'}"
    )


def _validate_for_commit(canvas: dict) -> None:
    """Validate canvas is ready to commit.

    Checks (spec §4.4):
      1. ≥ 2 steps COMPLETED
      2. No STALE steps
      3. Step 5 specifically COMPLETED (v2.0 MVP — no early-finalize)

    Note: this function does NOT check `final_concept` — final_concept is
    generated by step 2 of the commit handler AFTER step 1 invokes this
    function. Validation of the generated final_concept happens in step 3
    of the commit handler.
    """
    path = canvas.get("creative_path", [])
    completed = [p for p in path if p.get("state") == "completed"]
    if len(completed) < 2:
        raise HTTPException(
            status_code=422,
            detail={
                "error": True,
                "code": "INVALID_PATH",
                "message": "至少需要 2 步 COMPLETED",
                "detail": {},
            },
        )
    stale = [p for p in path if p.get("state") == "stale"]
    if stale:
        raise HTTPException(
            status_code=422,
            detail={
                "error": True,
                "code": "INVALID_PATH",
                "message": f"{len(stale)} 个 STALE 步骤需要处理",
                "detail": {},
            },
        )
    step5 = next((p for p in path if p.get("step") == 5), None)
    if not step5 or step5.get("state") != "completed":
        raise HTTPException(
            status_code=422,
            detail={
                "error": True,
                "code": "INVALID_PATH",
                "message": "Step 5 必须走完(v2.0 MVP 不支持早收束)",
                "detail": {},
            },
        )


# --- Pydantic models ---


class InitRequest(BaseModel):
    prompt: str = Field(..., min_length=1, max_length=_MAX_PROMPT_LEN)
    genre_primary: str = Field(..., min_length=1)
    genre_secondary: Optional[str] = None
    target_reader: Optional[str] = None
    reference_works: Optional[List[str]] = None
    forbidden_directions: Optional[List[str]] = None
    quick_mode: bool = False


class NextStepRequest(BaseModel):
    current_step: int = Field(..., ge=1, le=5)


class SelectRequest(BaseModel):
    step: int = Field(..., ge=1, le=5)
    option_id: str = Field(..., min_length=1)


# --- /init ---


def _empty_canvas_v4() -> dict:
    """Construct an empty v4 canvas skeleton (PRD §22).

    Used by:
      - POST /init (with root_idea + raw_intent populated by caller)
      - DELETE /state (resets session; root_idea + raw_intent preserved
        by copying them in from the existing canvas before write)

    Timestamps (`computed_at`, `created_at`, `last_modified_at`) reflect
    the time of construction; callers may overwrite `last_modified_at`
    on reset.
    """
    now = datetime.now(timezone.utc).isoformat()
    return {
        "schema_version": 4,
        "session_id": str(uuid.uuid4()),
        "root_idea": {
            "prompt": "",
            "genre": "",
            "premise": "",
            "extracted": {
                "genre": "",
                "core_elements": [],
                "potential_conflict": "",
            },
        },
        "raw_intent": {
            "prompt": "",
            "genre_primary": "",
            "genre_secondary": None,
            "target_reader": None,
            "reference_works": [],
            "forbidden_directions": [],
            "quick_mode": False,
            "trope_tags": [],
        },
        "creative_session": {
            "current_step": 1,
            "max_steps": 5,
            "status": "active",
        },
        "creative_path": [],
        "current_concept": {
            "premise": "",
            "core_conflict": "",
            "characters": [],
            "world_rules": [],
            "tropes": [],
            "themes": [],
            "novelty": 0.0,
        },
        "final_concept": None,
        "committed": False,
        "committed_at": None,
        "committed_concept_ref": "concept_and_dna.json",
        "scores": {
            "novelty": 0.0,
            "conflict": 0.0,
            "story_potential": 0.0,
            "uniqueness": 0.0,
            "computed_at": now,
        },
        "session_metadata": {
            "created_at": now,
            "last_modified_at": now,
            "elapsed_seconds": 0,
            "operation_count": 0,
        },
    }


@router.post("/session/init")
async def init_canvas_v2(project_id: str, body: InitRequest):
    """Initialize v2 canvas with raw_intent + root_idea dual-write.

    Writes PRD §22 enriched schema: root_idea (with extracted.genre +
    extracted.potential_conflict), creative_session, current_concept, top-level
    scores (with computed_at timestamp), session_metadata.elapsed_seconds, and
    committed_concept_ref (PRD §23.4).
    """
    _ensure_project(project_id)

    canvas = _empty_canvas_v4()
    canvas["root_idea"] = {
        "prompt": body.prompt,
        "genre": body.genre_primary,
        "premise": body.prompt,
        "extracted": {
            "genre": body.genre_primary,
            "core_elements": [],
            "potential_conflict": "",
        },
    }
    canvas["raw_intent"] = {
        "prompt": body.prompt,
        "genre_primary": body.genre_primary,
        "genre_secondary": body.genre_secondary,
        "target_reader": body.target_reader,
        "reference_works": body.reference_works or [],
        "forbidden_directions": body.forbidden_directions or [],
        "quick_mode": body.quick_mode,
        "trope_tags": [],
    }
    # Pre-populate creative_path with the step 1 entry so the UI can show
    # an "available" step 1 card immediately on init (matches PRD §22:
    # creative_path starts as a list with one available entry).
    now = canvas["scores"]["computed_at"]
    canvas["creative_path"] = [{
        "step": 1,
        "operation": None,
        "operation_reason": None,
        "options": [],
        "selected_option_id": None,
        "created_at": now,
        "selected_at": None,
        "regenerated_count": 0,
        "state": "available",
    }]
    canvas["current_concept"]["premise"] = body.prompt

    etag = _compute_etag(canvas)
    canvas["_etag"] = etag
    _write_canvas(project_id, canvas)

    return {"ok": True, "session_id": canvas["session_id"], "etag": etag}


# --- /state ---


@router.get("/session/state")
async def get_state_v2(project_id: str):
    canvas = _read_canvas(project_id)
    if canvas is None:
        raise HTTPException(
            status_code=404,
            detail={"code": "CANVAS_NOT_FOUND", "message": "画布未初始化"},
        )
    canvas["_etag"] = _compute_etag(canvas)
    return canvas


@router.delete("/session/state")
async def delete_canvas_state_v2(project_id: str) -> dict:
    """PRD §18.2: reset session, preserve root_idea.

    Preserves root_idea + raw_intent; wipes creative_path + scores +
    creative_session (back to step 1 / active). When no init has been
    done (no root_idea.prompt on disk), deletes canvas_state.json
    entirely so subsequent /init starts clean.
    """
    _ensure_project(project_id)
    canvas = _read_canvas(project_id)

    if canvas and canvas.get("root_idea", {}).get("prompt"):
        reset = _empty_canvas_v4()
        # Preserve root_idea + raw_intent + create timestamps
        reset["root_idea"] = canvas["root_idea"]
        reset["raw_intent"] = canvas.get("raw_intent", reset["raw_intent"])
        reset["session_metadata"]["created_at"] = (
            canvas.get("session_metadata", {}).get("created_at")
            or reset["session_metadata"]["created_at"]
        )
        reset["_etag"] = _compute_etag(reset)
        _write_canvas(project_id, reset)
    else:
        # No init ever done (or canvas missing) — delete the file so the
        # next /init writes a fresh slate.
        from backend.api.creative_diverge import _get_canvas_path
        path = _get_canvas_path(project_id)
        if path.exists():
            path.unlink()

    return {"ok": True, "reset": "session"}


# --- /next-step (impl extracted for testability) ---


async def _next_step_impl(project_id: str, current_step: int) -> dict:
    """Core logic for /next-step. Returns {step, operation, options, quality_warning}.

    Raises HTTPException on validation failure.
    """
    canvas = _read_canvas(project_id)
    if canvas is None:
        raise HTTPException(
            status_code=400,
            detail={"code": "CANVAS_NOT_INITIALIZED"},
        )

    if canvas["creative_session"]["current_step"] != current_step:
        raise HTTPException(
            status_code=409,
            detail={
                "code": "STEP_OUT_OF_SYNC",
                "message": (
                    f"expected step "
                    f"{canvas['creative_session']['current_step']}"
                ),
            },
        )

    # Compute deterministic op hint
    genres = [canvas["raw_intent"].get("genre_primary") or ""]
    if canvas["raw_intent"].get("genre_secondary"):
        genres.append(canvas["raw_intent"]["genre_secondary"])
    hint = compute_op_hint(
        canvas["current_concept"],
        canvas["creative_path"],
        current_step,
        genres=genres,
    )

    # Call LLM (single shot) via project's model_router.
    # Uses tier-1 (creative core) per CLAUDE.md routing.
    # See backend/llm/model_router.py + backend/services/llm_config.py.
    from backend.llm.model_router import get_model_router
    from backend.config import settings as _settings

    async def llm_call(context):
        router = get_model_router()
        # PRD §7: inject operation-aware A/B/C axis guidance so the three
        # generated options vary along the operation's axis instead of
        # being three rephrasings. `hint` is the deterministic op-hint from
        # compute_op_hint() — same source the LLM is told to consider via
        # candidate_operation_hint. If the LLM flips the operation, the
        # axis still applies to the originally-hinted op. The block is
        # formatted by the canonical helper in `option_generator` so the
        # YAML template and the module stay in lock-step.
        hint_for_axis = context.get("hint") or "twist"
        axis_block = format_axis_hint_block(hint_for_axis)
        user_prompt = (
            f"current_concept: {context.get('concept', {})}\n"
            f"selected_path: {context.get('selected_path', [])}\n"
            f"current_step: {context.get('step')}\n"
            f"max_steps: 5\n"
            f"candidate_operation_hint: {context.get('hint')}\n"
            f"\n{axis_block}\n"
        )
        system_prompt = _load_next_step_prompt()["system"]
        return await router.complete(
            tier="tier1",
            system=system_prompt,
            user=user_prompt,
            model=_settings.llm_model,
            max_tokens=2048,
            temperature=0.7,
        )

    parsed = await _call_llm_with_retry(llm_call, {
        "hint": hint,
        "concept": canvas["current_concept"],
        "step": current_step,
    })

    # Renumber option ids to be step-scoped (LLM prompt produces opt_a/b/c;
    # TreeCanvas looks up opt_{step}_{slot} so the UI can bind selections
    # back to the correct step and column).
    for idx, opt in enumerate(parsed["options"]):
        slot = ("a", "b", "c")[idx] if idx < 3 else f"x{idx}"
        opt["id"] = f"opt_{current_step}_{slot}"

    # Build path entry
    path_entry = {
        "step": current_step,
        "operation": parsed["operation"],
        "operation_reason": parsed.get("operation_reason", ""),
        "options": [{
            "id": o["id"],
            "title": o["title"],
            "premise": o["premise"],
            "logic": o.get("logic", ""),
            "scores": {},  # fire-and-forget NoveltyEvaluator will fill
        } for o in parsed["options"]],
        "selected_option_id": None,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "selected_at": None,
        "regenerated_count": 0,
        "state": "active",
    }

    # Ensure creative_path has an entry for this step (extend if needed)
    while len(canvas["creative_path"]) < current_step:
        canvas["creative_path"].append({
            "step": len(canvas["creative_path"]) + 1,
            "operation": None,
            "operation_reason": None,
            "options": [],
            "selected_option_id": None,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "selected_at": None,
            "regenerated_count": 0,
            "state": "locked",
        })

    canvas["creative_path"][current_step - 1] = path_entry
    transition_step_state(canvas, step=current_step, event="activate")
    canvas["_etag"] = _compute_etag(canvas)
    _write_canvas(project_id, canvas)

    return {
        "step": current_step,
        "operation": {
            "type": parsed["operation"],
            "name": parsed["operation"],
            "reason": parsed.get("operation_reason", ""),
        },
        "options": path_entry["options"],
        "quality_warning": None,
    }


@router.post("/session/next-step")
async def next_step_v2(project_id: str, body: NextStepRequest):
    return await _next_step_impl(project_id, body.current_step)


# --- /select ---


@router.post("/session/select")
async def select_option_v2(project_id: str, body: SelectRequest):
    """Mark step's selected_option_id; cascade-compute next step or finalize."""
    canvas = _read_canvas(project_id)
    if canvas is None:
        raise HTTPException(
            status_code=400,
            detail={"code": "CANVAS_NOT_INITIALIZED"},
        )

    path = canvas["creative_path"]
    if body.step > len(path):
        raise HTTPException(status_code=404, detail={"code": "STEP_NOT_FOUND"})

    entry = path[body.step - 1]
    if body.option_id not in [o["id"] for o in entry.get("options", [])]:
        raise HTTPException(
            status_code=422,
            detail={"code": "INVALID_OPTION_ID"},
        )

    entry["selected_option_id"] = body.option_id
    entry["selected_at"] = datetime.now(timezone.utc).isoformat()

    # Update current_concept from selected option
    selected = next(o for o in entry["options"] if o["id"] == body.option_id)
    canvas["current_concept"]["premise"] = selected.get(
        "premise", canvas["current_concept"]["premise"],
    )

    transition_step_state(canvas, step=body.step, event="complete")

    # PRD §16.1: after a selection, refresh top-level `scores` via
    # NoveltyEvaluator. NoveltyEvaluator.evaluate() is a SYNC method, so we
    # offload it to the default executor and cap the wait at 3s — a slow or
    # broken evaluator must never block the user's select action. The
    # evaluator returns scores on a 0-100 scale; canvas["scores"] is
    # normalized to 0-1 to match the schema initialized in _empty_canvas_v4.
    concept_for_eval = selected.get("premise", canvas["current_concept"]["premise"])
    canvas["scores"] = await _refresh_top_level_scores(project_id, concept_for_eval)

    # Write the completed step back so the in-memory state survives the
    # cascade re-read below.
    canvas["_etag"] = _compute_etag(canvas)
    _write_canvas(project_id, canvas)

    # Auto-trigger next step (or finalize at step 5)
    if body.step < 5:
        await _next_step_impl(project_id, body.step + 1)
        canvas = _read_canvas(project_id)
        canvas["_etag"] = _compute_etag(canvas)
        _write_canvas(project_id, canvas)
    # else: current_concept 收尾(final_concept 留给 /commit)

    return {
        "ok": True,
        "step": body.step,
        "selected_option_id": body.option_id,
    }


async def _refresh_top_level_scores(
    project_id: str, concept_for_eval: str, existing_scores: Optional[dict] = None,
) -> dict:
    """Run NoveltyEvaluator in the executor pool and map its 0-100 output
    to the canvas["scores"] 0-1 schema.

    Best-effort: any construction failure, timeout, or exception is logged
    and the existing scores are preserved (only `computed_at` is bumped).
    Never raises — the calling /select handler must always complete.
    """
    now_iso = datetime.now(timezone.utc).isoformat()

    def _run() -> "object":  # returns NoveltyScore or raises
        try:
            evaluator = _build_novelty_evaluator(project_id)
        except Exception as exc:  # construction-time import errors
            raise RuntimeError(f"NoveltyEvaluator build failed: {exc}") from exc
        if evaluator is None:
            raise RuntimeError("NoveltyEvaluator build returned None")
        return evaluator.evaluate(concept_for_eval)

    try:
        loop = asyncio.get_running_loop()
        new_score = await asyncio.wait_for(
            loop.run_in_executor(None, _run),
            timeout=3.0,
        )
        return {
            "novelty": round(new_score.trope_similarity_score / 100.0, 2),
            "conflict": round(new_score.contradiction_depth_score / 100.0, 2),
            "story_potential": round(new_score.market_saturation_score / 100.0, 2),
            "uniqueness": round(new_score.discussion_potential_score / 100.0, 2),
            "computed_at": now_iso,
        }
    except (asyncio.TimeoutError, Exception) as exc:
        _logger.warning("NoveltyEvaluator refresh failed in /select: %s", exc)
        return {**(existing_scores or {}), "computed_at": now_iso}


def _build_novelty_evaluator(project_id: str):
    """Construct a NoveltyEvaluator mirroring `/novelty` and `/whatif-expand`.

    Returns None on any construction failure (missing config files,
    missing project_dir, etc.) — the caller treats None as "skip refresh"
    and preserves the existing scores rather than 500ing the endpoint.
    """
    try:
        from backend.creative_os.novelty_evaluator import NoveltyEvaluator
        from backend.creative_os.trope_pool import TropePool
        from backend.creative_os.contradiction_engine import ContradictionEngine

        project_dir = settings.projects_dir / project_id
        catalog_path = settings.projects_dir.parent / "config" / "trope_catalog.yaml"
        trope_pool = TropePool(project_dir=project_dir, catalog_path=catalog_path)
        return NoveltyEvaluator(
            trope_pool=trope_pool,
            contradiction_engine=ContradictionEngine(),
            model_router=None,
            embedder=None,
        )
    except Exception as exc:
        _logger.warning("Could not build NoveltyEvaluator for %s: %s", project_id, exc)
        return None


# --- /commit ---


@router.post("/session/commit")
async def commit_canvas_v2(project_id: str):
    """v2 commit endpoint — delegates to v1.x logic.

Both v1.x `/creative/diverge/commit` and v2 `/creative/canvas/{project_id}/session/commit`
share the same downstream logic; the only difference is the new validation
order (validate → generate → validate → write). v1.x handler was refactored
in Task 8 to use this order.
    """
    from backend.api.creative_diverge import commit_canvas as _v1_commit
    return await _v1_commit(project_id, {})


# --- /evaluate (PRD §26 deprecated alias) ---


@router.post("/session/evaluate")
async def evaluate_deprecated_alias(project_id: str, response: Response) -> dict:
    """PRD §26: /evaluate is deprecated. Frontend should not call this;
    next-step auto-fills option.scores. Kept for v1.x compat callers.
    """
    response.headers["Deprecation"] = "true"
    canvas = _read_canvas(project_id)
    return {
        "deprecated": True,
        "warning": "Use option.scores from /next-step instead.",
        "current_scores": canvas.get("scores", {}) if canvas else {},
    }


