"""Verify /commit's _validate_for_commit enforces the 5 invariants (spec §4.4).

Note: this function must NOT check final_concept — final_concept is
generated by step 2 of /commit AFTER step 1 calls this function.
"""
import pytest
from backend.api.v2_canvas import _validate_for_commit
from backend.api import creative_diverge as cd
from fastapi import HTTPException


def _canvas(states):
    return {"creative_path": [
        {"step": i + 1, "state": s,
         "selected_option_id": "x" if s == "completed" else None}
        for i, s in enumerate(states)
    ]}


def test_validate_passes_for_5_completed_no_stale():
    _validate_for_commit(_canvas(["completed"] * 5))  # should not raise


def test_validate_fails_when_fewer_than_2_completed():
    with pytest.raises(HTTPException) as exc:
        _validate_for_commit(_canvas(["completed", "active", "locked", "locked", "locked"]))
    assert exc.value.status_code == 422
    assert "INVALID_PATH" in str(exc.value.detail)


def test_validate_fails_when_stale_present():
    with pytest.raises(HTTPException) as exc:
        _validate_for_commit(_canvas(["completed", "completed", "stale", "locked", "locked"]))
    assert exc.value.status_code == 422


def test_validate_fails_when_step_5_not_completed():
    with pytest.raises(HTTPException) as exc:
        _validate_for_commit(_canvas(["completed"] * 4 + ["active"]))
    assert "Step 5" in str(exc.value.detail)


def test_validate_does_not_check_final_concept():
    """Critical: final_concept is null at this point (generated in step 2)."""
    canvas = _canvas(["completed"] * 5)
    canvas["final_concept"] = None  # explicitly null
    _validate_for_commit(canvas)  # must not raise
